[package]
name = "elix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time="0.2.27"
brotli="3.3.0"
autodiscover-rs="0.1.0"
clap = "3.0.0-beta.2"
byteorder = "1.4.3"
progress-streams = "1.0.0"
